FROM node:15 AS builder
WORKDIR /app

COPY ./frontend /app
RUN yarn global add @vue/cli@3.7.0 sw-precache
RUN yarn install & yarn build & yarn sw-precache --config /app/frontend/sw-config.js & cp service-worker.js /app/frontend/dist/service-worker.js

FROM python:3.7-slim
WORKDIR /app
COPY --from=builder /app /app/frontend
COPY ./backend /app/backend

RUN pip install -r /app/backend/requirements.txt

CMD python /app/backend/manage.py runserver 0.0.0.0:$PORT

