FROM node:15 AS builder
WORKDIR /app

COPY ./frontend /app
RUN yarn install & yarn build

FROM python:3.7-buster
WORKDIR /app
COPY --from=builder /app /app/frontend
COPY . /app
RUN pip install django

CMD python /app/manage.py runserver 0.0.0.0:8000

