# Generated by Django 3.2.2 on 2021-07-03 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_profile_cpf_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, max_digits=11)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('time', models.IntegerField()),
                ('created_at', models.DateField()),
                ('name', models.CharField(max_length=60)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
