# Generated by Django 3.2.2 on 2021-07-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
