# Generated by Django 3.2.2 on 2021-05-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiwrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktimeseries',
            options={'verbose_name_plural': 'Stocks time series'},
        ),
    ]
