# Generated by Django 3.2.2 on 2021-05-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiwrapper', '0002_alter_stocktimeseries_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktimeseries',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
