# Generated by Django 3.2.2 on 2021-06-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiwrapper', '0003_stocktimeseries_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('variation', models.FloatField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stocktimeseries',
            unique_together={('ticker', 'frequency')},
        ),
    ]
