# Generated by Django 3.2.2 on 2021-06-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiwrapper', '0004_auto_20210630_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinquotation',
            name='sell',
            field=models.FloatField(blank=True),
        ),
    ]
