# Generated by Django 3.2.2 on 2021-06-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiwrapper', '0005_alter_coinquotation_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinquotation',
            name='sell',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
