# Generated by Django 3.2.2 on 2021-07-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiwrapper', '0006_alter_coinquotation_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('selic', models.FloatField()),
                ('cdi', models.FloatField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
