# Generated by Django 3.2.2 on 2021-07-05 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiwrapper', '0007_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='bitcoin',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='eur',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='ibovespa',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='nasdaq',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='usd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
