# Generated by Django 3.2.2 on 2021-05-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cpf_number',
        ),
    ]
