# Generated by Django 3.2.2 on 2021-07-05 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_auto_20210703_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
