# Generated by Django 3.2.2 on 2021-07-05 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_delete_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operations',
            options={'verbose_name_plural': 'Operations'},
        ),
    ]
